const Database = require('better-sqlite3');
const db = new Database('contactos.db');
const rows = db.prepare('SELECT nombre, categoria, telefono_maps, telefono_web, correo, whatsapp, instagram, facebook, tiktok, direccion, web, url_maps, busqueda, metodo, estado FROM negocios').all();
console.log('Total rows:', rows.length);
rows.forEach((r, i) => {
  console.log('\n--- Row ' + (i+1) + ' ---');
  console.log('Nombre:', r.nombre);
  console.log('Categoria:', r.categoria);
  console.log('Tel Maps:', r.telefono_maps);
  console.log('Tel Web:', r.telefono_web);
  console.log('Correo:', r.correo);
  console.log('WhatsApp:', r.whatsapp);
  console.log('Instagram:', r.instagram);
  console.log('Facebook:', r.facebook);
  console.log('TikTok:', r.tiktok);
  console.log('Direccion:', r.direccion);
  console.log('Web:', r.web);
  console.log('URLMaps:', r.url_maps);
  console.log('Busqueda:', r.busqueda);
  console.log('Metodo:', r.metodo);
  console.log('Estado:', r.estado);
});